#图形验证码配置
kaptcha:
  height: 40
  width: 150
  content:
    length: 4
    source: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIGKLMNOPQRSTUVWXYZ
    space: 3
  font:
    color: blue
    name: 宋体,楷体,微软雅黑
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1

#分页配置
pagehelper:
 auto-dialect: mysql
 reasonable: true
 support-methods-arguments: true
 params: count=countSql
#JACKSON 
spring:  
  jackson:     
    date-format: "yyyy-MM-dd"     
    time-zone: "GMT+8" 